variables:
    projectname: shoe-ShoppingCart
    version: 0.0.1-SNAPSHOT
    projectpath: /data/$projectuser
    projectuser: shoeshop
stages:
    - build
    - deploy
    - showlog
build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - whoami
        - pwd
        - ls
        - mvn install -DskipTests=true
    tags:
        - gitlab-server
    only:
        - tags
deploy:
    stage: deploy
    when: manual
    variables:
        GIT_STRATEGY: none
    script:
        - > 
            if [ "$GITLAB_USER_LOGIN" == "mahito" ]; then
                sudo cp target/$projectname-$version.jar $projectpath
                sudo chown $projectuser. $projectpath -c 
                sudo kill -9 $(ps -ef | grep shoe-ShoppingCart-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}')
                sudo su $projectuser -c "cd $projectpath; nohup java -jar $projectname-$version.jar > nohup.out 2>&1 &"
            else
                echo "Permission denied"
                exit 1
            fi
    tags:
        - gitlab-server
    only:
        - tags
showlog:
    stage: showlog
    when: manual
    variables:
        GIT_STRATEGY: none
    script:
        - sudo su $projectuser -c "cd $projectpath; tail -n 10000 nohup.out"
    tags:
        - gitlab-server
    only:
        - tags
