stages:
    - build
    - deploy
    - showlog
build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - sudo cp -r . /data/todolist
        - sudo chown todolist. /data/todolist -c
    tags:
        - gitlab-server
    only:
        - tags
deploy:
    stage: deploy
    when: manual
    variables:
        GIT_STRATEGY: none
    script:
        - sudo kill -9 $(ps -ef | grep "node_modules/.bin/vue-cli-service serve" | grep -v grep | awk '{print $2}')
        - sudo su todolist -c "cd /data/todolist; npm install; npm run build; nohup npm run serve 2>&1 &"
    tags:
        - gitlab-server
    only:
        - tags
showlog:
    stage: showlog
    when: manual
    variables:
        GIT_STRATEGY: none
    script:
        - sudo su todolist -c "cd /data/todolist; tail -n 10000 nohup.out"
    tags:
        - gitlab-server
    only: 
        - tags
